// <auto-generated />
using System;
using FORUM_CZAT.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FORUM_CZAT.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220601164609_NewPostMethod")]
    partial class NewPostMethod
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("FORUM_CZAT.Entities.EntityNewPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Astronomy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptoCurrencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Life")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mathematic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Programming")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Psychology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SciFi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Science")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NewPosts");
                });

            modelBuilder.Entity("FORUM_CZAT.Entities.EntityPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
